name: SurvivalGames
version: ${project.version}
main: org.mcsg.survivalgames.SurvivalGames
authors: [Double0negative, n3wton, TheFish97]
description: Fully Automated Hunger Games Plugin!
depend: [TabAPI]

commands:
    survivalgames:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [sg, hungergames, hg]

