name: SurvivalGames
version: ${plugin.version}
main: org.mcsg.survivalgames.SurvivalGames
authors: [Narimm, Addstar, Double0Negative]
api-version: ${spigot.api.version}
description: Fully Automated Hunger Games Plugin!
load: POSTWORLD
depend: [WorldEdit]
commands:
    survivalgames:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [sg, hungergames, hg]

